# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generateimage_pb2 as generateimage__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in generateimage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerateImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CanGenerate = channel.unary_unary(
                '/generateImage.GenerateImage/CanGenerate',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=generateimage__pb2.CanGenerateResponse.FromString,
                _registered_method=True)
        self.GenerateImage = channel.unary_unary(
                '/generateImage.GenerateImage/GenerateImage',
                request_serializer=generateimage__pb2.GenerateImageRequest.SerializeToString,
                response_deserializer=generateimage__pb2.GenerateImageRequestResponse.FromString,
                _registered_method=True)
        self.CheckGenerationStatus = channel.unary_unary(
                '/generateImage.GenerateImage/CheckGenerationStatus',
                request_serializer=generateimage__pb2.CheckGenerationStatusRequest.SerializeToString,
                response_deserializer=generateimage__pb2.CheckGenerationStatusResponse.FromString,
                _registered_method=True)
        self.RetrieveGeneratedImage = channel.unary_unary(
                '/generateImage.GenerateImage/RetrieveGeneratedImage',
                request_serializer=generateimage__pb2.RetrieveGenerateImageRequest.SerializeToString,
                response_deserializer=generateimage__pb2.RetrieveGeneratedImageResponse.FromString,
                _registered_method=True)


class GenerateImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CanGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckGenerationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveGeneratedImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerateImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CanGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.CanGenerate,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=generateimage__pb2.CanGenerateResponse.SerializeToString,
            ),
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=generateimage__pb2.GenerateImageRequest.FromString,
                    response_serializer=generateimage__pb2.GenerateImageRequestResponse.SerializeToString,
            ),
            'CheckGenerationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckGenerationStatus,
                    request_deserializer=generateimage__pb2.CheckGenerationStatusRequest.FromString,
                    response_serializer=generateimage__pb2.CheckGenerationStatusResponse.SerializeToString,
            ),
            'RetrieveGeneratedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveGeneratedImage,
                    request_deserializer=generateimage__pb2.RetrieveGenerateImageRequest.FromString,
                    response_serializer=generateimage__pb2.RetrieveGeneratedImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generateImage.GenerateImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generateImage.GenerateImage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerateImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CanGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generateImage.GenerateImage/CanGenerate',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            generateimage__pb2.CanGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generateImage.GenerateImage/GenerateImage',
            generateimage__pb2.GenerateImageRequest.SerializeToString,
            generateimage__pb2.GenerateImageRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckGenerationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generateImage.GenerateImage/CheckGenerationStatus',
            generateimage__pb2.CheckGenerationStatusRequest.SerializeToString,
            generateimage__pb2.CheckGenerationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveGeneratedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generateImage.GenerateImage/RetrieveGeneratedImage',
            generateimage__pb2.RetrieveGenerateImageRequest.SerializeToString,
            generateimage__pb2.RetrieveGeneratedImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
